### ISSUE TITLE
DevilutionX 1.5 Update

### ISSUE THREAD

**Issue by moonspam** [OnionUI/Ports-Collection#18]
DevilutionX has been updated to 1.5.
The folder structure of the 'devilutionx-miyoo-mini-onion-os.zip' file provided by the repository does not match the current 4.2.0 beta version, so I hope that the upgrade to version 1.5 can be applied.

https://github.com/diasurgical/devilutionX/releases/tag/1.5.0

**Comment by schmurtzm** [comment]
Done, will be published in the next version of port collection (v1.0.8)
https://github.com/OnionUI/Ports-Collection/commit/b12123d1a9ab7c53cbaf3293ab18e0fe685c6f24

**Comment by schmurtzm** [comment]
[v1.0.8 published](https://github.com/OnionUI/Ports-Collection/releases) with devilution 1.5, I close this one.
