### ISSUE TITLE
OpenTyrian not saving the game

### ISSUE THREAD

**Issue by blackkn1ght** [OnionUI/Ports-Collection#19]
Hi! I noticed the save function of OpenTyrian doesn't seem to work. If you manually save the game and then close it, no save games will be present when reopening the game from the Onion menu.

Thank you!

**Comment by schmurtzm** [comment]
Indeed , I see some errors :   
```
warning: failed to open 'tyrian.cfg': No such file or directory
Invalid or missing TYRIAN.CFG! Continuing using defaults.
warning: failed to open 'opentyrian.cfg': No such file or directory
warning: failed to open 'tyrian.sav': No such file or directory
```


For now I don't know why the game is not finding these files even when we create it manually 🤔
