### ISSUE TITLE
Ports shortcuts not working

### ISSUE THREAD

**Issue by jaxie** [OnionUI/Ports-Collection#21]
Many ports does not seem to run when using the shortcuts provided. For example DOOM 1 Ultimate (doomu.wad) works when loading the wad by running Retroarch manually and choosing core  Doom (PrBoom) and the wad file but does not start using [1 DOOM I - Ultimate (1993-95).port](https://github.com/OnionUI/Ports-Collection/blob/main/DOOM%20I%20-%20Ultimate%20(1993-95)%20(PrBoom)/Roms/PORTS/Shortcuts/FPS%20-%20Doom%20Collection%20(PrBoom)/1%20DOOM%20I%20-%20Ultimate%20(1993-95).notfound)

Running Miyoo Mini +
OS version: Onion 4.2.0-RC-snapshot-a5064207
Firmware: 202306092122

### runtime.log
:: Launch game
(runtime) 2023-09-20 23:49:03: rompath: /mnt/SDCARD/Roms/PORTS/Shortcuts/FPS - Doom Collection (PrBoom)/1 DOOM I - Ultimate (1993-95).port (ext: port)
(runtime) 2023-09-20 23:49:03: romcfgpath: /mnt/SDCARD/Roms/PORTS/Shortcuts/FPS - Doom Collection (PrBoom)/.game_config/1 DOOM I - Ultimate (1993-95).cfg
(runtime) 2023-09-20 23:49:03: ----- COMMAND:
(runtime) 2023-09-20 23:49:03: LD_PRELOAD=/mnt/SDCARD/miyoo/app/../lib/libpadsp.so "/mnt/SDCARD/Emu/PORTS/launch.sh" "/mnt/SDCARD/Roms/PORTS/Shortcuts/FPS - Doom Collection (PrBoom)/1 DOOM I - Ultimate (1993-95).port"
(runtime) 2023-09-20 23:49:03: cmd retval: 0
(runtime) 2023-09-20 23:49:03: state change: check_switcher
(runtime) 2023-09-20 23:49:03: state change: check_main_ui
(runtime) 2023-09-20 23:49:03:
:: Launch MainUI

### retroarch.log

[INFO] CPU Model Name: ARMv7 Processor rev 5 (v7l)
[INFO] Capabilities: NEON VFPv3 VFPv4
[INFO] Built: Jul 27 2023
[INFO] Version: 1.15.0
[INFO] =================================================
[INFO] [Input]: Found input driver: "sdl_dingux".
[INFO] [Core]: Loading dynamic libretro core from: ".retroarch/cores/prboom_libretro.so"
[INFO] [Overrides]: Core-specific overrides found at "/mnt/SDCARD/Saves/CurrentProfile/config/PrBoom/PrBoom.cfg".
[INFO] [Config]: Loading config: "/mnt/SDCARD/RetroArch//.retroarch/retroarch.cfg".
[INFO] [Config]: Appending override config: "/mnt/SDCARD/Saves/CurrentProfile/config/PrBoom/PrBoom.cfg".
[INFO] [Environ]: GET_CORE_OPTIONS_VERSION.
[INFO] [Environ]: SET_VARIABLES.
[INFO] [Environ]: SET_CONTROLLER_INFO.
[INFO] [Overrides]: Redirecting save file to "/mnt/SDCARD/Saves/CurrentProfile/saves/PrBoom/doomu.srm".
[INFO] [Overrides]: Redirecting save state to "/mnt/SDCARD/Saves/CurrentProfile/states/PrBoom/doomu.state".
[INFO] [Environ]: GET_LOG_INTERFACE.
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] [Environ]: PERFORMANCE_LEVEL: 4.
[INFO] [Content]: Content loading skipped. Implementation will load it on its own.
[INFO] [Environ]: GET_RUMBLE_INTERFACE.
[libretro INFO] Rumble environment supported.
[libretro ERROR] FindFileInDir: not found doomu in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[libretro ERROR] FindFileInDir: not found doomu in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[libretro ERROR] FindFileInDir: not found doomu in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[INFO] [Environ]: SYSTEM_DIRECTORY: "/mnt/SDCARD/BIOS".
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/BIOS/prboom
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/BIOS
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/Roms/PORTS/Games/Doom
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/Roms/PORTS/Games
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/Roms/PORTS
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD/Roms
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt/SDCARD
[libretro ERROR] FindFileInDir: not found prboom.cfg in /mnt
[INFO] [Environ]: GET_SAVE_DIRECTORY.
[libretro INFO] M_LoadDefaults: Load system defaults.
[libretro INFO]  default file: /mnt/SDCARD/Saves/CurrentProfile/saves/PrBoom/doomu/prboom.cfg
[libretro INFO] IdentifyVersion: basesavegame: /mnt/SDCARD/Saves/CurrentProfile/saves/PrBoom/doomu
[libretro INFO] iwad: /mnt/SDCARD/Roms/PORTS/Games/Doom/doom/doomu.wad
[libretro INFO] IWAD found: /mnt/SDCARD/Roms/PORTS/Games/Doom/doom/doomu.wad
[libretro ERROR] FindFileInDir: not found prboom.wad in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[INFO] [Environ]: SYSTEM_DIRECTORY: "/mnt/SDCARD/BIOS".
[libretro ERROR] FindFileInDir: not found prboom.wad in /mnt/SDCARD/BIOS/prboom
[libretro INFO] PrBoom, playing: The Ultimate DOOM
PrBoom is released under the GNU General Public license v2.0.
You are welcome to redistribute it under certain conditions.
It comes with ABSOLUTELY NO WARRANTY. See the file COPYING for details.
[libretro INFO] V_Init: allocate screens.
[libretro INFO] D_InitNetGame: Checking for network game.
[libretro INFO] W_Init: Init WADfiles.
[libretro INFO]  adding /mnt/SDCARD/Roms/PORTS/Games/Doom/doom/doomu.wad
[libretro INFO]  adding /mnt/SDCARD/BIOS/prboom.wad
[libretro INFO] W_InitCache
[libretro INFO]
[libretro INFO] M_Init: Init miscellaneous info.
[libretro INFO] R_Init: Init DOOM refresh daemon - [libretro INFO]
R_LoadTrigTables: [libretro INFO] Endianness...[libretro INFO] ok.[libretro INFO]
R_InitData: [libretro INFO] Textures [libretro INFO] Flats [libretro INFO] Sprites [libretro INFO] Colormaps [libretro INFO]
R_Init: R_InitPlanes [libretro INFO] R_InitLightTables [libretro INFO] R_InitSkyMap [libretro INFO] R_InitTranslationsTables [libretro INFO] R_InitPatches [libretro INFO]
P_Init: Init Playloop state.
[libretro INFO] I_Init: Setting up machine state.
[libretro INFO] I_InitSound:
[libretro INFO] I_InitMusic
[libretro INFO] S_Init: Setting up sound.
[libretro INFO] S_Init: default sfx volume 8
[libretro INFO] HU_Init: Setting up heads up display.
[libretro INFO] V_InitMode: using 16 bit video mode
[libretro INFO] ST_Init: Init status bar.
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/Roms/PORTS/Games/Doom/doom
[INFO] [Environ]: SYSTEM_DIRECTORY: "/mnt/SDCARD/BIOS".
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/BIOS/prboom
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/BIOS
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/Roms/PORTS/Games/Doom
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/Roms/PORTS/Games
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/Roms/PORTS
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD/Roms
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt/SDCARD
[libretro ERROR] FindFileInDir: not found intro.mp3 in /mnt
[libretro INFO] S_ChangeMusic: playing 'intro'
[INFO] [State]: found_last_state_slot: #0
[INFO] [Replay]: Found last replay slot: #0
[INFO] [SRAM]: Skipping SRAM load.
[INFO] [Core]: Version of libretro API: 1, Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 44100.00 Hz.
[INFO] [Video]: Set video size to: 320x240.
[INFO] [CPU]: Path not found: /mnt/SDCARD/Saves/CurrentProfile/config/PrBoom/cpuclock.txt
[INFO] [CPU]: Path not found: ./cpuclock.txt
[INFO] [Joypad]: Found joypad driver: "sdl_dingux".
[INFO] [Video]: Found display server: "null".
[ERROR] Failed to initialize audio driver. Will continue without audio.
[INFO] [Display]: Found display driver: "null".
[INFO] [Environ]: SET_INPUT_DESCRIPTORS:
[INFO] [Playlist]: Loading history file: "/mnt/SDCARD/Saves/CurrentProfile/lists/content_history.lpl".
[INFO] [Playlist]: Loading history file: "/mnt/SDCARD/Saves/CurrentProfile/lists/content_music_history.lpl".
[INFO] [Playlist]: Loading favorites file: "/mnt/SDCARD/Saves/CurrentProfile/lists/content_favorites.lpl".
[ERROR] failed_to_start_audio_driver
[INFO] [Config]: Loading config: "/mnt/SDCARD/RetroArch//.retroarch/retroarch.cfg".
[INFO] [Overrides]: Configuration overrides unloaded, original configuration restored.
[ERROR] failed_to_start_audio_driver
[INFO] [Core]: Content ran for a total of: 00 hours, 00 minutes, 00 seconds.
[INFO] [Core]: Unloading game..
[INFO] [Core]: Unloading core..
[libretro INFO] D_DoomDeinit:
[INFO] [Core]: Unloading core symbols..
[INFO] [Core]: Saved core options file to "/mnt/SDCARD/Saves/CurrentProfile/config/PrBoom/PrBoom.opt".
[INFO] [Autoconf]: Dingux Gamepad disconnected from port 1.
[INFO] [Video]: Does not have enough samples for monitor refresh rate estimation. Requires to run for at least 4096 frames.`

**Comment by schmurtzm** [comment]
Strange, seems related to audio driver...

- Unzip again the full collection port on your SD card
- Reset you retroarch configuration in Tweaks app
- Start you Miyoo without SD card , go in settings, Fixes, check if "Audio Fix" is ON

**Comment by jaxie** [comment]
Thank you, it seems to have done the trick. I would guess it might have been some RetroArch setting  or something corrupt from copying the Ports collection earlier. The Audio Fix was already ON.
