### ISSUE TITLE
Doom mod SIGIL II

### ISSUE THREAD

**Issue by 2Bane** [OnionUI/Ports-Collection#26]
A new SIGIL II Doom WAD launched today. I've created a _required_files.txt, Img, and .notfound for the new WAD.

Its running but I have not done a serious play test of it yet.

I'm very new to github can someone review this before I make a pull request.

https://github.com/2Bane/Ports-Collection

I'm unsure if I should also update the _required_files.txt for the other Doom 1 ports. Not sure what standard practices is there.

**Comment by schmurtzm** [comment]
Tested, seems good to me, your PR will be welcome 👍🏻
Thank you!
