### ISSUE TITLE
Port request  - blockout 2.

### ISSUE THREAD

**Issue by th0m4sek** [OnionUI/Ports-Collection#27]
I  have zero programming skill but loved this game from always.
I would love see this port happening.
http://www.blockout.net/blockout2/

**Comment by schmurtzm** [comment]
You don't really need a port blockout or blockout 2, DosBox is enough : 
![image](https://github.com/OnionUI/Ports-Collection/assets/7110113/c416b0e0-ed1a-4f0e-8148-3eb3404d656a)

Or is there some specific features that you want from this port ?

**Comment by th0m4sek** [comment]
Thanks, exactly what i wanted to achieve.
