### ISSUE TITLE
Blood and Cryptic Passage

### ISSUE THREAD

**Issue by theVanZan** [OnionUI/Ports-Collection#3]
I noticed the zip files and contents are the same for both the main game and it's addon Crytpic Passage. How can I have the choice of playing the main game or the addon?

**Comment by schmurtzm** [comment]
There is an error indeed `Roms/PORTS/Games/Blood - Cryptic Passage (nblood)` should not exist, all the data from main game and it's addon Crytpic Passage should be in the same directory : `Roms/PORTS/Games/Blood (nblood)/`.


Then there are 2 different shortcuts  : 
[Blood (nblood).notfound](https://github.com/OnionUI/Ports-Collection/blob/main/Blood%20(nblood)/Roms/PORTS/Shortcuts/FPS/Blood%20(nblood).notfound#L8)
[Blood - Cryptic Passage (nblood).notfound](https://github.com/OnionUI/Ports-Collection/blob/main/Blood%20-%20Cryptic%20Passage%20(nblood)/Roms/PORTS/Shortcuts/FPS/Blood%20-%20Cryptic%20Passage%20(nblood).notfound#L8)

As you can see each shortcut has its own "GameDataFile" , this is this file which will be detected by the import script.  It means that if you have the file "BLOOD.RFF" in your folder you will see blood in the list of "roms" (after launching the import script) and if you have also "CP01.MAP" thenk you'll see Crytpic Passage shortcut too.

I'll push a fix tonight for the `Roms/PORTS/Games/Blood - Cryptic Passage (nblood)` which should not exist.

**Comment by theVanZan** [comment]
Hey by thew way thanks for all your hard work man. I deleted the other folder. However I noticed that if I have the cryptic addon files in with the main blood files BOTH shortcuts start cryptic passage.

I deleted the Cryptic files and now I can start the original game.

Not a big deal. 90% of the ports are working fine thankfully.

**Comment by theVanZan** [comment]
Think I figured it out. You actually do need that second folder for cryptic passage. I then put all the data files into that second folder.

Most critically however I edited the cryptic passage shortcut. It was pointing at the folder for the base game rather than for cryptic passage.

Now I have everything perfect! :) Hope this helps someone.

**Comment by schmurtzm** [comment]
No no, you don't need both folders and you don't need to edit the shortcuts. Having only one "Blood (nblood)" folder is the good way. 
I have pushed the fix and [a new `_required_files.txt` easier to understand](https://github.com/OnionUI/Ports-Collection/blob/main/Blood%20(nblood)/Roms/PORTS/Games/Blood%20(nblood)/_required_files.txt).

**Comment by schmurtzm** [comment]
Can you give me information about the 10% which are not working for you ? ;)
